---
- name: pacman ~> Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest

- name: pacman ~> install dnf plugins
  package:
    name:
      - dnf-plugins-core
    state: present

- name: pacman ~> enable power tools
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version >= "8"

- name: update yum cache
  yum:
    update_cache: yes

- name: yum ~> upgrade all packages
  yum:
    name: '*'
    state: latest
  when: zeus_upgrade_first