variants:
  dev:
    debug:
    gcov:
    phpdbg:
  olympus:
    bz2:
    bcmath:
    calendar:
    ctype:
    curl:
    dba:
    dom:
    dtrace:
    editline:
    embed:
    exif:
    fileinfo:
    filter:
    fpm:
    ftp:
    gd:
    gettext:
    gmp:
    hash:
    iconv:
    imap:
    inifile:
    inline:
    intl:
    ipc:
    ipv6:
    json:
    kerberos:
    ldap:
    libgcc:
    mbregex:
    mbstring:
    mcrypt:
    mhash:
    mysql:
    opcache:
    openssl:
    pcntl:
    pcre:
    pdo:
    pear:
    pgsql:
    phar:
    posix:
    readline:
    session:
    soap:
    sockets:
    sodium:
    sqlite:
    static:
    tidy:
    tokenizer:
    wddx:
    xml:
    xmlrpc:
    zip:
    zlib:
    zts:

extensions:
  dev:
    xhprof: latest
    xdebug: stable
