---
- name: chrome ~> Define chrome_package.
  set_fact:
    chrome_package: "{{ __chrome_package }}"
  when: chrome_package is not defined

- name: chrome ~> check if chrome already installed
  command: "dpkg-query -W {{ chrome_package_name }}"
  register: _chrome_installed_version
  changed_when: false
  failed_when: false

- name: chrome ~> Set decision to install Google Chrome
  set_fact:
    chrome_install: "{{ _chrome_installed_version.rc == 1 }}"

- name: Download Google Chrome package
  get_url:
    url: "{{ chrome_download_url }}/{{ chrome_package }}"
    dest: /tmp/
  when: chrome_install

- name: Install Google Chrome package
  apt:
    deb: "/tmp/{{ chrome_package }}"
    state: present
  when: chrome_install
