- name: virtualbox ~> add apt-key 2016
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: virtualbox ~> add apt-key secondary
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: virtualbox ~> add apt-repository
  apt_repository:
    repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: virtualbox ~> install
  package:
    name: virtualbox
    state: present
